Start of Worklist build
galasa-dev-archives/webui-old pull request #111
Opened 2021-04-21 17:06 UTC by jadecarino

Signed-off-by: Jade Carino <jade.carino@ibm.com>

2021-04-21 17:20 UTC, jadecarino commented
Hi Mike, I have started developing the frontend for the Worklist. I have created the injectable Worklist service, and a Worklist component which receives the Worklist from the service and displays it on the panel (Run name and Result visible, whole Test class in tooltip). I've added a checkbox column to the table but I am having trouble because when you click on it, the row click takes precedence and takes you through to the Run page, it doesn't click the checkbox, so I haven't been able to test any logic to do with checking and unchecking the boxes. However to test the Worklist for now, I have added the first 3 tests from the table to the Worklist, if you go to the next page of the table, the first 3 tests from that page should be added to the Worklist, but if you go back a page they should not be added as the ID is found already in the list. 
Please can you review my progress and approach so far and let me know your thoughts?

2021-04-21 17:20 UTC, jadecarino commented
@Michael-Baylis

2021-04-22 09:22 UTC, Michael-Baylis requested changes
generating hard coded data needs to be changed.

I don't see the worklist entry data class.

2021-04-22 09:22 UTC, Michael-Baylis commented on src/app/results-page/rasfilters/results-table/results-table.component.ts
> +                for (let i = 0; i < 3; i++){
I can see the idea,   but I don't believe this will help with testing. as it will mean the first 3 in the table are always checked.
Find 3 specific tests and get their ras ids and use those in the hardcoded list, in the worklist service.

2021-04-22 13:41 UTC, jadecarino commented
Hi Mike please see my new changes - I've created a class for the Worklist data and the Worklist itself now holds an array of these data structures. If any of the tests from the Jenkins job are loaded on to the page they are added to the Worklist. As their IDs are unique I just search for them by Test class name. @Michael-Baylis

2021-04-27 08:02 UTC, Michael-Baylis requested changes
Almost there,    just need to change the way you initialise the test data,  you are trying to be too clever.

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/results-page/rasfilters/results-table/results-table.component.ts
> +                  if (run.testStructure.testName == "bulktest.bristol.cambridge.manchester.Osprey" || run.testStructure.testName == "bulktest.bristol.cambridge.chester.GoldenEagle"){
Why is this in the result-table.component.ts.   You are missing the point :-)

this part of the check should be calling the worktable service to see if it should be checked,  not the otherway round.

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklist.service.ts
> +  constructor() { }
At this point here,  you should be pre-initialising the worklist array with the 3-4 runs you want to be in the work list table.

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklist.service.ts
> +  constructor() { }
You will need to HARD CODE the runids.   this is only temporary until you include the code to add/remove runs to the table

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklist.service.ts
> +  addToWorklist(worklistItem : WorklistData){
Parameter should only be the RAS runid,    when the API is called, you will send the rasrunid and the api will return the updated data,  so dont pass more data than is necessary.

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklist.service.ts
> +  removeFromWorklist(worklistItem : WorklistData){
as with add,  only parameter should be the rasrunid

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklist.service.ts
> +    if (this.worklist.some(item => item.id == worklistItem.id)){
Uncessary,  it API will deal with this.   reason,    if you have 2 browser sessions running updating the same table

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklist.service.ts
> +    if (this.worklist.some(item => item.id == worklistItem.id)){
None of the following is necessary, handled by the api,  reason in case you have two browser sessions.

2021-04-27 08:02 UTC, Michael-Baylis commented on src/app/worklist/worklistdata.ts
> +    testClass : string;
Need shortname as well,   which is what will be displayed in panel

2021-04-27 10:56 UTC, Michael-Baylis approved these changes

2021-04-27 10:58 UTC, merged