Test result icons added and Run Overview component refactored
galasa-dev-archives/webui-old pull request #42
Opened 2021-01-13 15:49 UTC by jadecarino

2021-01-13 16:37 UTC, CJMeek submitted a review, later dismissed

2021-01-14 14:19 UTC, Michael-Baylis requested changes
Looking good,  changes required unfortunately

2021-01-14 14:19 UTC, Michael-Baylis commented on src/app/date-time/date-time.component.html
> +<p>{{dateTime}}</p>
should this be a `<div>` not a `<p>` .   Using div means the datetime could be instream.  `<p>` will start a new paragraph

2021-01-14 14:19 UTC, Michael-Baylis commented on src/app/date-time/date-time.component.ts
> +    return (year + "-" + month + "-" + date + " " + time + timeMillis);
dont need the millis

2021-01-14 14:19 UTC, Michael-Baylis commented on src/app/date-time/date-time.component.ts
> +    var localDateTime = new Date(value);
The dates from Galasa will always be in UTC/GMT.   How does this routine report the date/time in LOCAL browser timezone?

2021-01-14 14:19 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/run-detail.component.html
> +<p>{{value}}</p>
`<div>` not `<p>`

2021-01-14 14:19 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/test-result/test-result.component.html
> +<div class='inline-block-element' *ngIf="iconIsPass">
instead of lots of booleans,  I would do the condition on the string.
eg *ngIf="state = 'passed'"
cant remember the exact syntax.
That way, if new states are added, you only need to change this one pressentation layer file.
in the ts file,  lower case the state in to the variable.

2021-01-14 14:19 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/test-result/test-result.component.ts
> +  iconIsPass : boolean = false;
lowercased version of the state string instead of multiple booleans to handle future new states a lot easier

2021-01-18 10:47 UTC, jadecarino commented
Signed-off-by: Jade Carino jade.carino@ibm.com

2021-01-18 10:48 UTC, jadecarino commented
Signed-off-by: Jade Carino <jade.carino@ibm.com>

2021-01-18 11:07 UTC, jadecarino reviewed
changes complete

2021-01-18 13:25 UTC, Michael-Baylis requested changes
Date processing needs work, sorry

2021-01-18 13:25 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/test-result/test-result.component.ts
> +    }
else {
   this.state = "unknown"
}

2021-01-18 13:25 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/test-result/test-result.component.ts
> +    }
otherwise if you had a state,   then moved to run without a state,    state will be left as the previous run's state

2021-01-18 13:25 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/test-result/test-result.component.html
> +<div class='inline-block-element' *ngIf="state===null">
see comment lower,   state='unknown'

2021-01-18 13:25 UTC, Michael-Baylis commented on src/app/date-time/date-time.component.ts
> +  getLocalDateTime(value : string){
Sorry,  really not happy with this solution,  too much can go wrong.   Date time processing is essential so there must be a defacto standard typescript/npm library we can use to do the work.

2021-01-19 12:15 UTC, jadecarino commented on src/app/date-time/date-time.component.ts
> +  getLocalDateTime(value : string){
Hi Mike, I thought this solution was too simple, but it seems by simply creating a new Date object and passing it the date time string from the API, that will return it in the local time of the computer. TypeScript's Date object is designed to contain the date and time of the user's computer. I've changed my Mac's timezone to test it and it works so I've committed this solution, just wanted to let you know it looks very simple.

2021-01-20 10:03 UTC, Michael-Baylis requested changes
Date formatting and a petty little change

2021-01-20 10:03 UTC, Michael-Baylis commented on src/app/date-time/date-time.component.ts
> +  formatDate(localDateTime : Date){
Sorry Jade.    But the formatting should be to local browser settings.  eg,   uk dates are normally  99th Month Year,   in US it is Month, 99th, Year.
So you need to find the standard way of formatting the date/time to the browser locale

2021-01-20 10:03 UTC, Michael-Baylis commented on src/app/run-page/components/run-detail/test-result/test-result.component.ts
> +    else {
the else goes on the line above.  eg
} else {

2021-01-21 09:21 UTC, Michael-Baylis approved these changes

2021-01-21 13:25 UTC, CJMeek approved these changes

2021-01-21 13:28 UTC, closed without merging